Some fixes in CI pipeline

diff --git a/.github/workflows/build_and_deploy.yml b/.github/workflows/build_and_deploy.yml
--- a/.github/workflows/build_and_deploy.yml
+++ b/.github/workflows/build_and_deploy.yml
@@ -43,6 +43,7 @@ jobs:
       - name: Install non-Qt dependencies
         id: install_non_qt_deps
         run: |
+          sudo apt-get -qq update
           sudo apt-get -qq install cmake ninja-build p7zip-full coreutils curl
 
       - name: Install gcc
@@ -60,7 +61,6 @@ jobs:
       - name: Install Qt 5.12.8
         id: install_qt_old
         run: |
-          sudo apt-get -qq update
           sudo apt-get -qq install qtbase5-dev qttools5-dev qttools5-dev-tools libqt5webkit5-dev
         if: ${{ matrix.qt_version == '5.12.8' }}
 
@@ -362,10 +362,26 @@ jobs:
           export BRANCH_NAME=$(echo $GITHUB_REF | sed 's/.*\/\(.*\)$/\1/')
           gh api /repos/d1vanov/QEverCloud/releases/tags/continuous-${BRANCH_NAME} > /tmp/gh_get_release.json && exit_status=$? || exit_status=$?
           if [ "${exit_status}" = 0 ]; then
-            export COMMIT_SHA=$(cat /tmp/gh_get_release.json | jq '.target_commitish');
+            export COMMIT_SHA=$(cat /tmp/gh_get_release.json | jq '.target_commitish')
             if ! [ "${COMMIT_SHA}" = "${GITHUB_SHA}" ]; then
-              gh release delete continuous-${BRANCH_NAME} -y -R d1vanov/QEverCloud;
-              curl -X DELETE -H "Authorization: token ${GITHUB_TOKEN}" -H "Accept: application/vnd.github.v3+json" https://api.github.com/repos/d1vanov/QEverCloud/git/refs/tags/continuous-${BRANCH_NAME};
+              export PREVIOUS_CONTINUOUS_RELEASE_DELETED=0
+              for i in {1..10}
+              do
+                echo "Trying to delete previous continuous release continuous-${BRANCH_NAME}"
+                gh release delete continuous-${BRANCH_NAME} -y -R d1vanov/QEverCloud;
+                curl -X DELETE -H "Authorization: token ${GITHUB_TOKEN}" -H "Accept: application/vnd.github.v3+json" https://api.github.com/repos/d1vanov/QEverCloud/git/refs/tags/continuous-${BRANCH_NAME};
+                gh api /repos/d1vanov/QEverCloud/releases/tags/continuous-${BRANCH_NAME} > /tmp/gh_get_release.json && exit_status=$? || exit_status=$?
+                if [ "${exit_status}" != 0 ]; then
+                  echo "It appears that previous continuous release is deleted now"
+                  export PREVIOUS_CONTINUOUS_RELEASE_DELETED=1
+                  break
+                fi
+                echo "Was able to receive information about the attempted to be deleted previous continuous release, waiting for 5 seconds before the next attempt"
+                sleep 5
+              done
+              if [ "$PREVIOUS_CONTINUOUS_RELEASE_DELETED" != "1" ]; then
+                echo "Failed to delete previous continuous release after several attempts!"
+              fi
             fi
           fi
         shell: bash
@@ -392,8 +408,9 @@ jobs:
         env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
           GITHUB_REF: ${{ github.ref }}
+          GITHUB_REF_NAME: ${{ github.ref_name }}
         run: |
-          gh release create "$GITHUB_REF" --draft=false --title "Release build ($GITHUB_REF)" -R d1vanov/QEverCloud
+          gh release create "$GITHUB_REF" --draft=false --title "Release build ($GITHUB_REF_NAME)" -R d1vanov/QEverCloud
 
       - name: Download linux artifact
         id: download_linux_artifact
@@ -702,6 +719,6 @@ jobs:
         if: ${{ github.ref != 'refs/heads/master' && github.ref != 'refs/heads/development' }}
         env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-          GITHUB_REF: ${{ github.ref }}
+          GITHUB_REF_NAME: ${{ github.ref_name }}
         run: |
-          gh release edit "$GITHUB_REF" --draft=false -R d1vanov/QEverCloud
+          gh release edit "$GITHUB_REF_NAME" --draft=false -R d1vanov/QEverCloud
